#include "main.h"
#include "bms_can.h"
#include "bms_data.h"
#include "bms_config.h"
#include "bms_state.h"
#include "bms_faults.h"

/* CAN handle generated by CubeMX */
extern CAN_HandleTypeDef hcan;

/* -------------------------------------------------------------------------- */
/* Private CAN variables                                                      */
/* -------------------------------------------------------------------------- */

static CAN_RxHeaderTypeDef rx_header;
static uint8_t rx_data[8];

static uint8_t can_running = 0U;

/* Pending command flags */
static uint8_t status_request_pending = 0U;
static uint8_t fault_reset_pending = 0U;
static uint8_t enable_request_pending = 0U;
static uint8_t disable_request_pending = 0U;

/* -------------------------------------------------------------------------- */
/* Private helper functions                                                   */
/* -------------------------------------------------------------------------- */

static HAL_StatusTypeDef BMS_CAN_ConfigureFilter(void)
{
    CAN_FilterTypeDef filter;

    filter.FilterBank = 0U;
    filter.FilterMode = CAN_FILTERMODE_IDMASK;
    filter.FilterScale = CAN_FILTERSCALE_32BIT;

    /*
     * Standard CAN ID occupies bits [10:0].
     * HAL filter register uses the ID shifted left by 5 bits.
     */
    filter.FilterIdHigh =
        (uint16_t)((BMS_CAN_COMMAND_ID << 5U) & 0xFFFFU);

    filter.FilterIdLow = 0U;

    filter.FilterMaskIdHigh =
        (uint16_t)((0x7FFU << 5U) & 0xFFFFU);

    filter.FilterMaskIdLow = 0U;

    filter.FilterFIFOAssignment = CAN_FILTER_FIFO0;
    filter.FilterActivation = ENABLE;
    filter.SlaveStartFilterBank = 14U;

    return HAL_CAN_ConfigFilter(&hcan, &filter);
}

/* -------------------------------------------------------------------------- */
/* Public functions                                                           */
/* -------------------------------------------------------------------------- */

void BMS_CAN_Start(void)
{
    if (HAL_CAN_GetState(&hcan) != HAL_CAN_STATE_READY)
    {
        return;
    }

    if (BMS_CAN_ConfigureFilter() != HAL_OK)
    {
        can_running = 0U;
        BMS_Data.can_rx_active = 0U;
        BMS_Data.can_tx_active = 0U;
        return;
    }

    if (HAL_CAN_Start(&hcan) != HAL_OK)
    {
        can_running = 0U;
        BMS_Data.can_rx_active = 0U;
        BMS_Data.can_tx_active = 0U;
        return;
    }

    if (HAL_CAN_ActivateNotification(
            &hcan,
            CAN_IT_RX_FIFO0_MSG_PENDING) != HAL_OK)
    {
        HAL_CAN_Stop(&hcan);

        can_running = 0U;
        BMS_Data.can_rx_active = 0U;
        BMS_Data.can_tx_active = 0U;
        return;
    }

    can_running = 1U;

    BMS_Data.can_rx_active = 1U;
    BMS_Data.can_tx_active = 1U;
}

/* -------------------------------------------------------------------------- */

void BMS_CAN_SendTestMessage(void)
{
    CAN_TxHeaderTypeDef tx_header;
    uint8_t tx_data[8];
    uint32_t tx_mailbox;

    int32_t voltage_raw;
    int32_t current_raw;
    int32_t temperature_raw;
    int32_t soc_raw;
    int32_t soh_raw;

    if (can_running == 0U)
    {
        return;
    }

    /*
     * Status message:
     *
     * ID = 0x100
     * DLC = 8
     *
     * Byte 0-1 : Battery voltage x10
     * Byte 2-3 : Battery current x10, signed
     * Byte 4   : SOC %
     * Byte 5   : Temperature in deg C, signed
     * Byte 6   : SOH %
     * Byte 7   : Fault status
     */

    tx_header.StdId = BMS_CAN_STATUS_ID;
    tx_header.ExtId = 0U;
    tx_header.IDE = CAN_ID_STD;
    tx_header.RTR = CAN_RTR_DATA;
    tx_header.DLC = 8U;
    tx_header.TransmitGlobalTime = DISABLE;

    /* ---------------- Battery voltage ---------------- */

    voltage_raw =
        (int32_t)(BMS_Data.battery_voltage * 10.0f);

    if (voltage_raw < 0)
    {
        voltage_raw = 0;
    }

    if (voltage_raw > 65535)
    {
        voltage_raw = 65535;
    }

    tx_data[0] = (uint8_t)((uint16_t)voltage_raw >> 8);
    tx_data[1] = (uint8_t)((uint16_t)voltage_raw & 0xFFU);

    /* ---------------- Battery current ---------------- */

    current_raw =
        (int32_t)(BMS_Data.battery_current * 10.0f);

    if (current_raw > 32767)
    {
        current_raw = 32767;
    }

    if (current_raw < -32768)
    {
        current_raw = -32768;
    }

    {
        int16_t current_encoded = (int16_t)current_raw;

        tx_data[2] =
            (uint8_t)((uint16_t)current_encoded >> 8);

        tx_data[3] =
            (uint8_t)((uint16_t)current_encoded & 0xFFU);
    }

    /* ---------------- SOC ---------------- */

    soc_raw =
        (int32_t)BMS_Data.state_of_charge;

    if (soc_raw < 0)
    {
        soc_raw = 0;
    }

    if (soc_raw > 100)
    {
        soc_raw = 100;
    }

    tx_data[4] = (uint8_t)soc_raw;

    /* ---------------- Temperature ---------------- */

    temperature_raw =
        (int32_t)BMS_Data.battery_temperature;

    if (temperature_raw < -128)
    {
        temperature_raw = -128;
    }

    if (temperature_raw > 127)
    {
        temperature_raw = 127;
    }

    tx_data[5] = (uint8_t)((int8_t)temperature_raw);

    /* ---------------- SOH ---------------- */

    soh_raw =
        (int32_t)BMS_Data.state_of_health;

    if (soh_raw < 0)
    {
        soh_raw = 0;
    }

    if (soh_raw > 100)
    {
        soh_raw = 100;
    }

    tx_data[6] = (uint8_t)soh_raw;

    /* ---------------- Fault status ---------------- */

    tx_data[7] = BMS_Data.fault_status;

    if (HAL_CAN_AddTxMessage(
            &hcan,
            &tx_header,
            tx_data,
            &tx_mailbox) == HAL_OK)
    {
        BMS_Data.can_tx_count++;
    }
}

/* -------------------------------------------------------------------------- */

void BMS_CAN_ProcessCommands(void)
{
    /*
     * All command processing occurs in the main loop.
     * The CAN interrupt only stores the received command.
     */

    if (status_request_pending != 0U)
    {
        status_request_pending = 0U;
        BMS_Data.status_request = 0U;

        /*
         * Immediately transmit the current BMS status.
         */
        BMS_CAN_SendTestMessage();
    }

    /* ---------------- Fault reset command ---------------- */

    if (fault_reset_pending != 0U)
    {
        fault_reset_pending = 0U;
        BMS_Data.fault_reset_request = 0U;

        BMS_Faults_RequestReset();
        BMS_State_RequestRecovery();
    }

    /* ---------------- Enable command ---------------- */

    if (enable_request_pending != 0U)
    {
        enable_request_pending = 0U;

        /*
         * The CAN module does not directly change system_enabled.
         * It sends an enable request to the state machine.
         */
        BMS_State_RequestEnable();
    }

    /* ---------------- Disable command ---------------- */

    if (disable_request_pending != 0U)
    {
        disable_request_pending = 0U;

        BMS_State_RequestDisable();
    }
}

/* -------------------------------------------------------------------------- */

uint8_t BMS_CAN_StatusRequestPending(void)
{
    return status_request_pending;
}

/* -------------------------------------------------------------------------- */

void BMS_CAN_ClearStatusRequest(void)
{
    status_request_pending = 0U;
    BMS_Data.status_request = 0U;
}

/* -------------------------------------------------------------------------- */

uint8_t BMS_CAN_FaultResetPending(void)
{
    return fault_reset_pending;
}

/* -------------------------------------------------------------------------- */

void BMS_CAN_ClearFaultResetRequest(void)
{
    fault_reset_pending = 0U;
    BMS_Data.fault_reset_request = 0U;
}

/* -------------------------------------------------------------------------- */

uint8_t BMS_CAN_IsRunning(void)
{
    return can_running;
}

/* -------------------------------------------------------------------------- */
/* CAN receive interrupt callback                                             */
/* -------------------------------------------------------------------------- */

void HAL_CAN_RxFifo0MsgPendingCallback(CAN_HandleTypeDef *hcan_callback)
{
    if (hcan_callback != &hcan)
    {
        return;
    }

    if (HAL_CAN_GetRxMessage(
            hcan_callback,
            CAN_RX_FIFO0,
            &rx_header,
            rx_data) != HAL_OK)
    {
        return;
    }

    /*
     * Accept only:
     *   - Standard ID
     *   - Data frame
     *   - Command message ID
     *   - At least one data byte
     */

    if (rx_header.IDE != CAN_ID_STD)
    {
        return;
    }

    if (rx_header.RTR != CAN_RTR_DATA)
    {
        return;
    }

    if (rx_header.StdId != BMS_CAN_COMMAND_ID)
    {
        return;
    }

    if (rx_header.DLC < 1U)
    {
        return;
    }

    switch (rx_data[0])
    {
        case BMS_CAN_CMD_STATUS_REQUEST:
            status_request_pending = 1U;
            BMS_Data.status_request = 1U;
            break;

        case BMS_CAN_CMD_FAULT_RESET:
            fault_reset_pending = 1U;
            BMS_Data.fault_reset_request = 1U;
            break;

        case BMS_CAN_CMD_ENABLE:
            enable_request_pending = 1U;
            break;

        case BMS_CAN_CMD_DISABLE:
            disable_request_pending = 1U;
            break;

        default:
            /*
             * Unknown command.
             * Ignore it safely.
             */
            break;
    }

    BMS_Data.can_rx_count++;
}
